name: Deploy to Production

on:
  push:
    branches: [ main ]

env:
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
  STRIPE_MONTHLY_STANDARD_PRICE_ID: ${{ secrets.STRIPE_MONTHLY_STANDARD_PRICE_ID }}
  STRIPE_YEARLY_STANDARD_PRICE_ID: ${{ secrets.STRIPE_YEARLY_STANDARD_PRICE_ID }}
  STRIPE_MONTHLY_PREMIUM_PRICE_ID: ${{ secrets.STRIPE_MONTHLY_PREMIUM_PRICE_ID }}
  STRIPE_YEARLY_PREMIUM_PRICE_ID: ${{ secrets.STRIPE_YEARLY_PREMIUM_PRICE_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Build
      run: npm run build
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        STRIPE_MONTHLY_STANDARD_PRICE_ID: ${{ secrets.STRIPE_MONTHLY_STANDARD_PRICE_ID }}
        STRIPE_YEARLY_STANDARD_PRICE_ID: ${{ secrets.STRIPE_YEARLY_STANDARD_PRICE_ID }}
        STRIPE_MONTHLY_PREMIUM_PRICE_ID: ${{ secrets.STRIPE_MONTHLY_PREMIUM_PRICE_ID }}
        STRIPE_YEARLY_PREMIUM_PRICE_ID: ${{ secrets.STRIPE_YEARLY_PREMIUM_PRICE_ID }}
